services:
  postgres:
    image: postgres:15-alpine
    container_name: epicplay_db
    environment:
      POSTGRES_USER: epicplay_user
      POSTGRES_PASSWORD: epicplay_password
      POSTGRES_DB: epicplay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: epicplay_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app  # Sincroniza tu código local con el contenedor
    environment:
      - DB_HOST=postgres # Variable para que Python encuentre la BD

volumes:
  postgres_data: